apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: if2s14ocn-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/if2s14ocn-java-quarkus-gitops